bids_dir: /data/datasets/hemispherotomy
participants_tsv: /data/datasets/hemispherotomy/participants.tsv
target: AF # to be implemented: AF | CST | CC
seeding: roi # roi | wholebrain | frmi  
clustering:
  
