bids_dir: /home/justus/datasets/justus_kleine_denkmurmel
participants_tsv: /home/justus/datasets/justus_kleine_denkmurmel/participants.tsv
target: AF # to be implemented: AF | CST | CC
seeding: roi # roi | wholebrain | frmi  
clustering:
  
